services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  worker:
    build:
      context: .
      target: base
    environment:
      - CELERY_WORKER=1
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
    environment:
      - CELERY_WORKER=0
    depends_on:
      redis:
        condition: service_healthy

  monitor:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  redis_data: