version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - type: volume
        source: redis_data
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  worker:
    build: .
    environment:
      - CELERY_WORKER=1
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  web:
    build: .
    environment:
      - CELERY_WORKER=0
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy

  monitor:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  redis_data:
    driver: local